### PR TITLE
New MPF Device: Spinner!

### PR DESCRIPTION
**Pull request by avanwinkle**
### Spinner

This PR introduces a new Device type to MPF: the **Spinner**

The Spinner device provides a convenient mechanism for aggregating rapid switch hits and tracking when a "batch" of hits begins and ends. The Spinner is `active` while switch hits are occurring, `inactive` when switch hits stop for a given time, and `idle` after being inactive for a certain time.

```

spinners:
  basic_spinner:
    switch: s_orbit_spinner
    active_ms: 500
  dual_spinner:
    switches: s_top_loop_left, s_top_loop_right
    switch_tags: left, right
    active_ms: 1200
    idle_ms: 2400
```

The consolidated events allow the game to start light and sound shows that play during the spin without having to time/overlap the shows against the inconsistent switch hits. The extra `idle_ms` time can be used for slides or widgets that should persist longer than the spin but still be removed after a timeout.

### Basic Usage

The lifecycle:
1. Spinner sits, `idle: true` and `active: false`
2. The spinner switch is hit
    i. The device switches to `active: true` and sets a timeout for `active_ms` duration
    ii. The device posts _spinner_<name>_active_ event
    iii. The device posts _spinner_<name>_hit_ event
3. Additional switch hits occur
    i. The device resets the timeout for another `active_ms` duration
    ii. The device posts _spinner_<name>_hit_ event
4. Switch hits stop and the active delay timer expires
    i. The device switches to `active: false`
    ii. The device posts _spinner_<name>_inactive_ event
    iii. (Optional) If `idle_ms` is defined, the device sets a timeout for `idle_ms` duration
5. (Optional) No switch hits occur and the idle delay timer expires 
    i. The device posts _spinner_<name>_idle_ event
    ii. The device switches to `idle: true`

If no `idle_ms` is defined, the spinner will immediately go to (and post) its idle state when it turns inactive. If it is idle and new switch hits occur, the spinner will re-activate and the cycle starts over.

### Advanced Usage: Spinner Tags

In some situations it is useful to combine multiple spinner switches into a single spinner device—for example a series of inline spinners, or a horseshoe with a spinner at each entrance. If the designer wants to count *all* of the switch hits (either in aggregate or separately), but use a single `active_ms` and `idle_ms` for the group, the Spinner device supports that.

The Spinner config accepts multiple `switches:` (using the same pattern as Shots, either `switch:` or `switches:` can be defined as a single entry or list) and a hit to any switch will trigger the hit and active states. Optionally, the `switch_tags:` config can be defined that maps a tag to each switch. When defined, the Spinner will post both _spinner_<name>_hit_ and _spinner_<name>_<tag>_hit_ events with the tag of whichever switch triggered the hit.

> Question: I chose `switch_tags` because it's used in other configs, but would `switch_labels` or just `labels` be a better name?

### Sample Event Log

In the below log you can see a Spinner named _top_loop_ that is activated by an entrance on the left side and an exit on the right side. The switch hits are aggregated (_spinner_top_loop_hit_) and separated (_spinner_top_loop_left_hit_, _spinner_top_loop_right_hit_), and the Spinner deactivates and idles after it's `active_ms: 1000` and `idle_ms: 2000`.
```
2021-06-15 13:53:43,950 : ======'spinner_top_loop_active'======
2021-06-15 13:53:43,950 : ======'spinner_top_loop_left_active'======
2021-06-15 13:53:43,950 : ======'spinner_top_loop_hit'======
2021-06-15 13:53:43,950 : ======'spinner_top_loop_left_hit'======
2021-06-15 13:53:44,265 : ======'spinner_top_loop_hit'======
2021-06-15 13:53:44,265 : ======'spinner_top_loop_left_hit'======
2021-06-15 13:53:44,583 : ======'spinner_top_loop_hit'======
2021-06-15 13:53:44,583 : ======'spinner_top_loop_left_hit'======
2021-06-15 13:53:44,883 : ======'spinner_top_loop_hit'======
2021-06-15 13:53:44,883 : ======'spinner_top_loop_left_hit'======
2021-06-15 13:53:45,216 : ======'spinner_top_loop_hit'======
2021-06-15 13:53:45,216 : ======'spinner_top_loop_right_hit'======
2021-06-15 13:53:45,483 : ======'spinner_top_loop_hit'======
2021-06-15 13:53:45,483 : ======'spinner_top_loop_right_hit'======
2021-06-15 13:53:45,700 : ======'spinner_top_loop_hit'======
2021-06-15 13:53:45,700 : ======'spinner_top_loop_left_hit'======
2021-06-15 13:53:45,950 : ======'spinner_top_loop_hit'======
2021-06-15 13:53:45,950 : ======'spinner_top_loop_right_hit'======
2021-06-15 13:53:46,166 : ======'spinner_top_loop_hit'======
2021-06-15 13:53:46,166 : ======'spinner_top_loop_right_hit'======
2021-06-15 13:53:46,482 : ======'spinner_top_loop_hit'======
2021-06-15 13:53:46,482 : ======'spinner_top_loop_right_hit'======
2021-06-15 13:53:47,483 : ======'spinner_top_loop_inactive'======
2021-06-15 13:53:49,484 : ======'spinner_top_loop_idle'======
```

Spin!

### CODE REVIEW

**Comment by avanwinkle** [comment]
Putting this up as a draft, I'll work on tests but looking for feedback on the implementation. My first new Device type!

**Comment by jabdoa2** [comment]
Looks good. I like it. Will review the code later.

One question to the events:

```
2021-06-15 13:53:43,950 : ======'spinner_top_loop_active'======
2021-06-15 13:53:43,950 : ======'spinner_top_loop_left_active'======
```
Should we add the number or spins here? I guess people want to show that on slides. Guess that could be spins in the current active phase.

**Comment by jabdoa2** [comment]
> Question: I chose switch_tags because it's used in other configs, but would switch_labels or just labels be a better name?

I actually got confused by tag because I thought this would be switch tags. So label sounds better for me. Or even something such as "group".

**Review by jabdoa2 — APPROVED** [review]

**Comment by avanwinkle** [comment]
Thanks for the feedback! Changed `switch_tags` to `labels`, added the hits kwarg and an option `reset_when_inactive` to control whether the hit count resets on inactive state or idle state. Also, tests!

**Pull request merged**
