### PR TITLE
Virtual_pinball LED Brightness

### PR DESCRIPTION
**Pull request by 4starpizza**
Updates to virtual_pinball class to support sending floating point brightness to VPX. Existing methods will continue to work as-is by transmitting a boolean state for each light or LED.

### CODE REVIEW

**Comment by jabdoa2** [comment]
Very nice! Good way to keep backward compatiblity. I like it.

**Comment by 4starpizza** [comment]
How do I trigger a re-run of the checks?

**Comment by jabdoa2** [comment]
> How do I trigger a re-run of the checks?

Just commit more changes to your branch and it should pick them up.

**Comment by 4starpizza** [comment]
Could someone please approve the waiting workflow?

**Comment by jabdoa2** [comment]
Check. Sorry that i missed it

**Comment by 4starpizza** [comment]
Thank you!

**Pull request merged**
