### PR TITLE
1375 refactor machine variables

### PR DESCRIPTION
**Pull request by pmansukhani**
- I have moved machine variables to a new class "MachineVariables". 
- Test cases have been refactored. 
- New test cases added to class `TestMachineVariables`

**Pending**: 
- 1 test case is failing. I'm not sure why. Some insight would be helpful
- Squashing of commits: I will do this after fixing the test case.

### CODE REVIEW

**Comment by jabdoa2** [comment]
Looks good! That test is indeed weird. Looks like it is only failing on windows and Mac. Linux passes. Might be some race. I will have a look.

The linter has some nits:

```
Messages
========
mpf/core/machine_vars.py
  Line: 58
    pep257: D105 / Missing docstring in magic method
  Line: 61
    pep257: D105 / Missing docstring in magic method
  Line: 64
    pep257: D102 / Missing docstring in public method
mpf/modes/credits/code/credits.py
  Line: 139
    pep8: E128 / continuation line under-indented for visual indent (col 42)
    pep8: E128 / continuation line under-indented for visual indent (col 42)
  Line: 159
    pep8: E128 / continuation line under-indented for visual indent (col 48)
    pep8: E128 / continuation line under-indented for visual indent (col 48)
mpf/platforms/fast/fast_serial_communicator.py
  Line: 130
    pep8: E501 / line too long (126 > 120 characters) (col 121)
mpf/plugins/auditor.py
  Line: 133
    pep8: E501 / line too long (130 > 120 characters) (col 121)
```

**Comment by pmansukhani** [comment]
Could you share the command to run the linter?

**Comment by jabdoa2** [comment]
We use prospector. Use "pip3 install prospector==1.1.6.3" to install it. The latest release has a bug so we have to pin to the latest working version currently. Just run "prospector" inside the repository.

**Comment by pmansukhani** [comment]
I'm getting a LOT of messages on running the linter (698). Is there a way to filter them?

**Comment by jabdoa2** [comment]
Python duck typing hid this error. Basically `_monitor_machine_vars` created `machine_var_monitor` in `MachineController` when called. Unit test look good now (at least locally for me)

**Comment by pmansukhani** [comment]
@jabdoa2  Thanks for helping out :)

**Comment by avanwinkle** [comment]
This is a breaking change for release 0.53 for anybody who accesses machine variables directly in python code. 

Previously:
```
self.machine.set_machine_var("foo", bar)
```

New:
```
self.machine.variables.set_machine_var("foo", bar)
```

**Pull request merged**
