### PR TITLE
Conditional event handlers and asset groups

### PR DESCRIPTION
**Pull request by avanwinkle**
This PR adds functionality in `event_player` to support the use of conditions on event _handlers_ in addition to the triggers. For example:

```
reenable_nonrecruit_modes:
    - start_mode_shadowbroker_base
    - start_mode_n7_assignments
    # Prior to collectorship, enable overlord; afterwards, enable arrival
    - start_mode_overlordlight{device.achievements.collectorship.state!="complete"}
    - start_mode_arrival{device.achievements.collectorship.state=="complete"}
```

This update also includes conditional support for asset pools (e.g. `sound_pools`) that evaluate the inclusion of assets during random/sequential selection:
```
sound_pools:
  randomsquad_recruitcomplete:
    type: random
    track: voice
    sounds:
      - missioncomplete_voice_miranda
      - missioncomplete_voice_jack
      - missioncomplete_voice_garrus{current_player.status_garrus<=1}
      - missioncomplete_voice_jack{current_player.status_jack<=1}
      - missioncomplete_voice_grunt{current_player.status_grunt<=1}
      - missioncomplete_voice_mordin{current_player.status_mordin<=1}
      - missioncomplete_voice_samara{current_player.status_samara<=1}
 ```

### THE LOGIC
This PR adds a new method to `placeholder_manager` called `parse_conditional_template()`, which standardizes the parsing of a template string (e.g. _"some_event_name{condition!=False}|2"_) that was previously duplicated across players. This method returns a dictionary object as follows:
```
parse_dict = { 
    name: "some_event_name", 
    condition: <BoolTemplate 'condition!=False'>, 
    number: 2
}
```
The method supports an optional keyword argument `default_number`. If provided, the method will attempt to type-conform the template's number value to match the `default_number` type, or populate the default value if the template has no number specified. If not provided, the method will return the template's number value in its original string form (e.g. _"500ms"_)

### THE IMPLEMENTATION
The `parse_conditional_template` method is implemented in `EventPlayer` to determine whether each event handler in a list should be posted, and is done in realtime so that condition changes mid-mode are always reflected. Currently the event player parses the handler strings every time the trigger is activated, but future work might store the parsed strings (with names, conditions, and delays) the way asset pools do.

The `parse_conditional_template` method is also implemented in `AssetPool` to determine which assets should be considered during random/sequential selection. The condition templates are instantiated on init but evaluated when an asset is requested from the pool, so condition changes mid-mode are always reflected. If a pool has no conditional assets, all conditional logic is bypassed (for speed).

Basic handling is provided for pools in which every asset condition is false, but this scenario has not been thoroughly tested (and should probably be discouraged).

### CODE REVIEW

**Review by jabdoa2 — COMMENTED** [review]
Looks awesome! Can you have a look at the linter messages? https://travis-ci.org/missionpinball/mpf/jobs/330100445#L1361. If you want you can run prospector (install via pip) locally to get the same messages. 

I will test it locally and probably merge this tomorrow.

**Comment by avanwinkle** [comment]
Ah hah, prospector! I was wondering what the CI builder was, happy to check things on my side before committing.

Hopefully you can help me with the test stability on `test_EventPlayer.py`. On my machine I get full passes every time, but on Travis each run has 2-4 of the 4 instances fail on asserting an event was called. I've tried adding machine cycles and changing the assertions, but those tests (specifically `test_handler_condition()`) are very unstable 😢

**Comment by avanwinkle** [comment]
P.S. Travis is failing with the following error:
 **`pylint: failure / Tool pylint failed to run (exception was raised)`**

Tracking it down, the cause is in *mpf/core/utility_functions.py*, line 710-715:
```
try:
    done, pending = yield from asyncio.wait(iter(futures), loop=loop, timeout=timeout,
               return_when=asyncio.FIRST_COMPLETED)
except asyncio.CancelledError:
    Util.cancel_futures(futures)
    raise
```
which yields the following crash:
```
Traceback (most recent call last):
  File "bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "lib/python3.6/site-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "lib/python3.6/site-packages/pylint/lint.py", line 980, in check_astroid_module
    walker.walk(ast_node)
  File "lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "lib/python3.6/site-packages/pylint/utils.py", line 1014, in walk
    self.walk(child)
  File "lib/python3.6/site-packages/pylint/utils.py", line 1011, in walk
    cb(astroid)
  File "lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 362, in visit_raise
    self._check_stop_iteration_inside_generator(node)
  File "lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 374, in _check_stop_iteration_inside_generator
    if exc is not None and self._check_exception_inherit_from_stopiteration(exc):
  File "lib/python3.6/site-packages/pylint/checkers/refactoring.py", line 381, in _check_exception_inherit_from_stopiteration
    return any(_class.qname() == stopiteration_qname for _class in exc.mro())
TypeError: 'Uninferable' object is not iterable
```

The utility_functions.py file hasn't been changed in a while, and those particular lines in over a year. Not sure why it's failing now.

**Comment by jabdoa2** [comment]
Thanks for the fast response! The crash is a pylint bug. Don't worry about it. I reported it upstream and the fix will be included in the next release: https://github.com/PyCQA/pylint/issues/1779. I will have a look at the unstable tests.

**Comment by jabdoa2** [comment]
The flanky tests were actually caused by the event order. The first condition which evaluates to false would prevent the evaluation of any further events (order in YAML is not deterministic). Fixed it in my last commit.

**Comment by avanwinkle** [comment]
Thanks for catching that! I've been out of Python too long, forgetting that `break` and `continue` are different things.

Doh!

**Pull request merged**
