### PR TITLE
Modified and extended 16segment "font"

### PR DESCRIPTION
**Pull request by cobra18t**

### CODE REVIEW

**Comment by jabdoa2** [comment]
I would prefer to replace the existing 16segment mappings. Yours seem to be strickl better to me. Do you see any reason to keep the old ones? I think the lower case letters were extrapolated from other mappings (with less segments).

**Comment by cobra18t** [comment]
I am fine with replacing it. I was not sure if people were already using the existing one and preferred it. I you do not think so, I can just replace the existing.

**Comment by jabdoa2** [comment]
> I am fine with replacing it. I was not sure if people were already using the existing one and preferred it. I you do not think so, I can just replace the existing.

Those are relatively new and yours are better. There isnt much hardware for it out yet with MPF support.

**Comment by cobra18t** [comment]
I updated everything to overwrite the existing font and eventually got it to pass the automated tests.

**Comment by jabdoa2** [comment]
Awesome. Thanks!

**Pull request merged**
