### PR TITLE
Enable ball saves to be sourced from a lock

### PR DESCRIPTION
**Pull request by cobra18t**

### CODE REVIEW

**Comment by cobra18t** [comment]
This code was pulled heavily from the multiball.py device code, so I believe it is sound. I have done MPF Monitor testing with it and it performed as expected, but I need help with an automated test for this.

**Comment by jabdoa2** [comment]
Awesome! Thanks!

**Comment by jabdoa2** [comment]
For some reason this PR broke on of our tests in the docs:
```
$ mpf test game_logic/multiballs/multiball_with_traditional_ball_lock.rst 
Parsing documentation page
.F.
======================================================================
FAIL: test_config_parsing (mpf.tests.MpfDocTestCase.MpfDocTestCase)
Block 1 (starting at 0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jan/src/mpf/mpf/tests/MpfDocTestCase.py", line 216, in test_config_parsing
    method(*parts)
AssertionError: KABOOM! We just added a ball to lockdevice which has a capacity of 2 but already had 2 ball(s)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jan/src/mpf/mpf/tests/MpfDocTestCase.py", line 218, in test_config_parsing
    raise AssertionError("Error in assertion {} (Num: {}) of your tests.".format(command, line_no)) from e
AssertionError: Error in assertion add_ball_to_device (Num: 23) of your tests.

----------------------------------------------------------------------
Ran 3 tests in 0.423s

FAILED (failures=1)
```

You can find it here: https://docs.missionpinball.org/en/dev/game_logic/multiballs/multiball_with_traditional_ball_lock.html#using-a-multiball-lock-to-start-a-multiball. If you click on the example it will also show the test. @cobra18t Can you have a look?

**Comment by cobra18t** [comment]
How can you tell that it is PR 1607 and not PR 1608 that broke the test?

**Comment by cobra18t** [comment]
I rolled back the changes on PR 1608 and this error went away. I do not think this PR caused the issue. Will look into 1608.

**Comment by jabdoa2** [comment]
> I rolled back the changes on PR 1608 and this error went away. I do not think this PR caused the issue. Will look into 1608.

You are right. I commented on the wrong PR. I checked by checking out specific commits before and after merge. Theoretically, git bisect could also find this

**Comment by jabdoa2** [comment]
@cobra18t looks like @avanwinkle fixed this just in time: https://github.com/missionpinball/mpf-docs/pull/391/files

**Pull request merged**
