### PR TITLE
Add servo support for OPP

### PR DESCRIPTION
**Pull request by cobra18t**
Servos can be driven from OPP versions 2.2.0.2 and later. This PR adds support for that. Position and speed limiting are implemented. Acceleration is not something the firmware supports. 

Position has a 10us resolution. Speed is configured so a 1ms pulse transition--often considered "full range" on a servo--will take 1 minute with a speed of 1. The same move with a speed of 60 will take 1 second. Setting the speed <= 0 leads to step changes on position command (unrestricted speed).

Individual servo channels must be enabled in the OPP config or the pin will just act like an input.

### CODE REVIEW

**Comment by jabdoa2** [comment]
Very clean and well done. Thanks!

**Comment by jabdoa2** [comment]
Thanks for the PR. Your change looks good. Could you add a small test as well? That would prevent us from accidentially breaking opp servos in the future.

**Comment by cobra18t** [comment]
I am struggling to write a test.

- The minimum required version is 2.2.0.2
- The expected command after machine_reset_phase_3 is: \x20\x40\x30\x00\x00\x01\x00\x00\x95
- The config section is:

> servos:
>   servo_test:
>     servo_min: 0
>     servo_max: 1
>     speed_limit: 20
>     reset_position: 0.588
>     reset_events: machine_reset_phase_3
>     number: 19088743-0-8

**Comment by jabdoa2** [comment]
> I am struggling to write a test.
> 
>     * The minimum required version is 2.2.0.2
> 
>     * The expected command after machine_reset_phase_3 is: \x20\x40\x30\x00\x00\x01\x00\x00\x95
> 
>     * The config section is:
> 
> 
> > servos:
> > servo_test:
> > servo_min: 0
> > servo_max: 1
> > speed_limit: 20
> > reset_position: 0.588
> > reset_events: machine_reset_phase_3
> > number: 19088743-0-8

If you want you can push your stuff to a branch (either this or a new one) and I can have a look.

**Comment by cobra18t** [comment]
It looks like the problem is in stopping of the servo. I have a stop method in the servo class, but probably the main OPP platform is shutting down before the OPPServo.stop() can complete. How do I tell the main platform to wait?

If I remove the stop method for the servo, the tests all pass. But I want a stop method to command the servo to disable before MPF shuts down. This did work on actual hardware and I am not sure what the error means. Here is the error:

`sudo python3 -m unittest test_OPP
..Failed to stop all tasks
E
======================================================================
ERROR: testOpp (test_OPP.TestOPPStm32)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mpf/tests/test_OPP.py", line 166, in tearDown
    super().tearDown()
  File "/usr/local/lib/python3.6/dist-packages/mpf/tests/MpfTestCase.py", line 958, in tearDown
    self.machine._do_stop()
  File "/usr/local/lib/python3.6/dist-packages/mpf/core/machine.py", line 729, in _do_stop
    self.shutdown()
  File "/usr/local/lib/python3.6/dist-packages/mpf/core/machine.py", line 774, in shutdown
    self.clock.loop.close()
  File "/usr/local/lib/python3.6/dist-packages/mpf/tests/loop.py", line 286, in close
    open_tasks = [t for t in tasks if (not t.done() and not isinstance(t.get_coro(), asyncio.Lock))]
  File "/usr/local/lib/python3.6/dist-packages/mpf/tests/loop.py", line 286, in <listcomp>
    open_tasks = [t for t in tasks if (not t.done() and not isinstance(t.get_coro(), asyncio.Lock))]
AttributeError: '_asyncio.Task' object has no attribute 'get_coro'

----------------------------------------------------------------------
Ran 3 tests in 0.168s

FAILED (errors=1)
`

**Comment by cobra18t** [comment]
I got the tests working after adding the expected servo disable command to tearDown. One of the Appveyor builds failed for a reason I cannot explain. Ideas?

**Comment by jabdoa2** [comment]
> I got the tests working after adding the expected servo disable command to tearDown. One of the Appveyor builds failed for a reason I cannot explain. Ideas?

That has been some random failure in the build infrastructure. Reran the test and it is happy now.

**Pull request merged**
