### PR TITLE
README Documentation

### PR DESCRIPTION
**Pull request by austinbgill**
Edited README page:

-Broke up section headings
-Rearranged layout for smoothness
-Edited some text/verbiage

Really cool project! I think these edits make the page just a bit more accessible and easy to skim through essential info. Let me know what you think! I would be happy to contribute further.

### CODE REVIEW

**Comment by jabdoa2** [comment]
Awesome! Looks very good. Thanks for cleaning this up!

**Comment by avanwinkle** [comment]
Looks great, thanks Austin!

**Comment by jabdoa2** [comment]
If you want to contribute further you can have a look at the documentation: http://docs.missionpinball.org/en/dev/ or its source: https://github.com/missionpinball/mpf-docs/. Contributions to MPF and MPF-MC (the media controller) are welcome too

**Comment by austinbgill** [comment]
Sounds lovely! Thanks guys

**Pull request merged**
