### PR TITLE
Added DIY Pinball hardware support

### PR DESCRIPTION
**Pull request by abencz**
Support added for DIY Pinball hardware in MPF configuration. DIY Pinball
switch, driver, and matrix light devices supported.

See diypinball.ca for details about the DIY Pinball open source hardware.

### CODE REVIEW

**Comment by abencz** [comment]
I wasn't sure if this should go into 0.30 or dev. I have a branch ready to merge into dev as well, but I haven't been able to test it as I'm having trouble getting pyserial-asyncio installed. If this should go into dev, I'll close this PR and open one to dev once I get the pyserial situation sorted.

**Comment by jabdoa2** [comment]
Hi Alex,
this should go into dev. Looks good. Please have a look why the tests fail: https://ci.appveyor.com/project/toomanybrians/mpf/build/1.0.1292/job/of9ueo29f7ws51lf or https://travis-ci.org/missionpinball/mpf/jobs/156694347

You can install pyserial-asyncio using this command line: pip3 install https://github.com/pyserial/pyserial-asyncio/archive/master.zip. The probleme there is that they did not yet upload their package to pypi (see: https://github.com/pyserial/pyserial-asyncio/issues/9).

**Comment by abencz** [comment]
I think the test is failing because it's running on a version of Python3 < 3.3. The DIY Pinball code needs socketcan support which was added in Python 3.3: https://docs.python.org/3/library/socket.html?highlight=socket#module-socket

I think this could be resolved by forcing travis to use Python 3.3+: https://docs.travis-ci.com/user/languages/python/

Let me try it out on my fork.

**Comment by jabdoa2** [comment]
Where do you see Python 3.3? We build Python 3.4 and 3.5 and all of them are failing. Did you add your dependeny to setup.py?

**Comment by abencz** [comment]
There's no additional dependency, socketcan support is built into the `socket` module in Python 3.3+ on Linux.

I just noticed the failing tests are running in Windows & OSX :(, I don't think Windows/OSX have socketcan support - this is a Linux-only API.

Edit: Cross-platform support will be difficult because, at least in Windows, CAN support usually takes the form of a vendor-specific API library for a given CAN adapter. I don't know of a way to interface with a CAN device in a vendor-independent way outside of Linux.

**Comment by abencz** [comment]
@jabdoa2, would is be sufficient to disable this code on Windows/OSX for now?

**Comment by jabdoa2** [comment]
@abencz yes that would work. Can you create a new PR against dev?

Besides that a simple test would be nice. Since nobody of the MPF team has your hardware its hard for us to not break your platform accidentally.

Codingstyle looks good. Some docblocks for public methods, classes and modules would be nice.

**Pull request closed without merging**
